# Generated by Django 6.0.2 on 2026-02-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='dangerzone',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dangerzone',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='dangerzone',
            name='longitude',
        ),
        migrations.AddField(
            model_name='dangerzone',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dangerzone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dangerzone',
            name='risk_type',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Flood', 'Flood'), ('Landslide', 'Landslide')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
