# Generated by Django 6.0.2 on 2026-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_place_type_place_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerzone',
            name='location',
        ),
        migrations.AddField(
            model_name='dangerzone',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dangerzone',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
