# Generated by Django 6.0.2 on 2026-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_dangerzone_location_dangerzone_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangerzone',
            old_name='description',
            new_name='additional_details',
        ),
        migrations.AlterField(
            model_name='dangerzone',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dangerzone',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dangerzone',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
    ]
