# Generated by Django 6.0.2 on 2026-02-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_description_dangerzone_additional_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerzone',
            name='radius',
            field=models.IntegerField(default=500, help_text='Geofence radius in meters'),
        ),
    ]
